export class Persona {
    _id:string;
    cedula:string;
    nombre:string;
    apellido:string;
    date:String;
    configuraciones:boolean;
    linea:boolean;
    estado:boolean; 
    poseeLinea:boolean;
    constructor(){ 
        this._id="";
        this.cedula="";
        this.nombre="";
        this.apellido="";
        this.estado=false;
        this.configuraciones=false;
        this.linea=false;
        this.poseeLinea=false;
    }
}
